[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day6 = "4AJZvLUdKCaYAjjMgWMh9hsbprpi82HEPvUs3XCxpFBo"

[programs.devnet] 
day6 = "4AJZvLUdKCaYAjjMgWMh9hsbprpi82HEPvUs3XCxpFBo"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/muhammad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
